#!/bin/python3

from os import sys #To read stdin
from matrix import matrix
from make_info import make_info
import copy

def print_usage(): # -h
    print("USAGE\n\t./303make makefile [file]")
    print("DESCRIPTION\n\tmakefile\tname of the makefile")
    print("\tfile\tname of a recently modified file")

def parser():
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        print_usage()
        quit (0)
    elif (len(sys.argv) == 2):
        print("simple makefile")
    elif (len(sys.argv) == 3):
        print("second part")
    else :
        print_usage()
        quit (84) #exit
    try:
        with (open(sys.argv[1])) as file:
            data = file.read().rstrip().split('\n')
    except:
        quit (84)
    return data

data = parser()
save = data
print (data)

for element in data:
    if 'cc ' in element:
        data.remove(element)
data = [i for i in data if i]

list_file = []

for i in range(0, len(data) - 1):
    list_file.append(make_info(data[i], data[i]))
print (data)

print(list_file)
quit(0)


print (data)

