#!/bin/python3

from os import sys #To read stdin
from matrix import matrix
import copy

def print_usage(): # -h
    print("USAGE\n\t./303make makefile [file]")
    print("DESCRIPTION\n\tmakefile\tname of the makefile")
    print("\tfile\tname of a recently modified file")

def parser():
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        print_usage()
        quit (0)
    elif (len(sys.argv) == 2):
        print("simple makefile")
    elif (len(sys.argv) == 3):
        print("second part")
    else :
        print_usage()
        quit (84) #exit
    try:
        with (open(sys.argv[1])) as file:
            data = file.read().rstrip().split('\n')
    except:
        quit (84)
    return data

data = parser()
save = data

for element in data:
    if 'cc ' in element:
        data.remove(element)

data = [i for i in data if i]
data = [w.replace(':', ' ') for w in data]
data = [element.split() for element in data]

list_file = []

for element in data:
    for file in element:
        if not(file in list_file):
            list_file.append(file)
list_file.sort()

tab = matrix(len(list_file), len(list_file), None, list_file)

for element in data:
    for file in element[1:]:
        tab.matrix[tab.names.index(file)][tab.names.index(element[0])] = 1
tab.print_matrix()
print()
tab.read_matrix()

quit(0)